### ISSUE TITLE
Error	51	Failed to load msbuild Toolset

### ISSUE THREAD

**Issue by zengyunchun** [jchadwick/NuGet.Packer#14]
After install to my project, use release to build, it occurs this error that may be cannot find musbuild library , but after adding MSbuild reference in VS 2013 also could not work, is it only support VS 2015?
Details: Error	52	 cannot load file or assembly  “Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
@jchadwick

**Comment by jchadwick** [comment]
@zengyunchun I developed it in VS13 and never had any problems.  This doesn't seem like a Packer problem since it doesn't bring in any assembly references.  All it does it bring down the Nuget.exe and add tasks to your project.

Do you have a link to the project or more detailed build output?

**Comment by jchadwick** [comment]
Closing due to no follow-up
