### ISSUE TITLE
NuGetToolsPath is hard coded and can be wrong

### ISSUE THREAD

**Issue by sylvainlavoie** [jchadwick/NuGet.Packer#3]
in uGet.Packer.targets the path to Nuget.exe is defined to 
<NuGetToolsPath>$(SolutionDir)packages\NuGet.CommandLine.3.3.0\tools</NuGetToolsPath>

However if a nuget.config file change the default location of the packages, the path can be wrong.

<config>
    <add key="repositoryPath" value="..\..\..\Depends\packages" />
 </config>

Maybe the solution should be in Nuget.CommandLine to define a property for is location

**Comment by jchadwick** [comment]
Agreed.  Unfortunately, I don't own Nuget.CommandLine.  :)

**Comment by sylvainlavoie** [comment]
you may also fix it in you package.



```
<NugetPackageRoot Condition=" '$(NugetPackageRoot)'=='' ">$(MSBuildThisFileDirectory)..\..\</NugetPackageRoot>
<NuGetToolsPath Condition=" '$(NuGetToolsPath)'=='' ">$(NugetPackageRoot)NuGet.CommandLine.3.3.0\tools</NuGetToolsPath>
```

**Comment by jchadwick** [comment]
Ah, I see where you're going now!   That change looks great.  Care to send a PR?  :)

**Comment by sylvainlavoie** [comment]
PR ?
