### ISSUE TITLE
A dependency to NuGet.Packer is included in the created package

### ISSUE THREAD

**Issue by JechoJekov** [jchadwick/NuGet.Packer#6]
When a package is created `NuGet` automatically adds a dependency to all packages specified in `package.config` inside the project directory, including `NuGet.Packer`. This can be prevented by specifying that `NuGet.Packer` is used for development purposes only.

This is done by adding a property to `NuGet.Packer.nuspec` as explained here:

http://stackoverflow.com/questions/15012963/dont-include-dependencies-from-packages-config-file-when-creating-nuget-package

http://docs.nuget.org/release-notes/nuget-2.8#Development_Dependencies

**Comment by jchadwick** [comment]
Would love a pull request!  :)

**Comment by jchadwick** [comment]
Fixed with PR #7
