### ISSUE TITLE
I'm not sure how to fix such issue

### ISSUE THREAD

**Issue by ukushu** [jchadwick/NuGet.Packer#8]
Directly after install:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""F:\Programming\Other\BotAgent\packages\NuGet.Packer.1.2.1\build\..\..\NuGet.CommandLine.3.3.0\tools\NuGet.exe" pack "F:\Programming\Other\BotAgent\BotAgent.DataExporter\BotAgent.DataExporter.nuspec" -NonInteractive -BasePath "bin\Release" -OutputDirectory "bin\Release" -symbols -Version 1.0.16110317" exited with code 1.

**Comment by jchadwick** [comment]
Sorry, this is not enough info to help diagnose. Are you able to reproduce in another project that you can share on GitHub?

**Comment by ukushu** [comment]
You can find both projects with the same issue here:
https://skulptorrr@bitbucket.org/skulptorrr/botagent.ifrit.git
